### PR TITLE
When the commissioning is completed, the initial value is transmitted.

### PR DESCRIPTION
**Pull request by jinwon0325kim**
issue : https://github.com/Samsung/ioter/issues/25

### CODE REVIEW

**Comment by junyong-sim** [comment]
Could you explain why we have to send initial value after onboarding is completed ?

**Comment by jinwon0325kim** [comment]
> Could you explain why we have to send initial value after onboarding is completed ?

The value is transmitted to make the initial state of Things and the state of the ST app the same.

**Review by junyong-sim — APPROVED** [review]
LGTM

**Comment by sangsoolee** [comment]
Is this for https://github.com/Samsung/ioter/issues/25 ??

**Comment by jinwon0325kim** [comment]
> 

right

**Pull request merged**
