### PR TITLE
Limit max value of light sensor

### PR DESCRIPTION
**Pull request by spdkimo**
Problem: Max value of illuminance in Lux is 3.576 Mlx. But SmartThings limits its range to 100,000. MaxMeasuredValue attribute is not effect in this case.
Measure: Change the value to 100,000.

### CODE REVIEW

**Comment by junyong-sim** [comment]
How about changing below logic, too ?

`lightsensor.py`
```
def set_state(self):
        if Utils.toIlluminance(self.measured_value) >= 50000:
            self.labelStatePicture.setPixmap(Utils.get_icon_img(
                Utils.get_icon_path('lightsensor_high.png'), 70, 70))
        elif 10000 <= Utils.toIlluminance(self.measured_value) < 50000:
            self.labelStatePicture.setPixmap(Utils.get_icon_img(
                Utils.get_icon_path('lightsensor_medium.png'), 70, 70))
        else:
            self.labelStatePicture.setPixmap(Utils.get_icon_img(
                Utils.get_icon_path('lightsensor_low.png'), 70, 70))
```

**Comment by spdkimo** [comment]
According to https://en.wikipedia.org/wiki/Lux, 320–500 is typical office lighting
I agree that current condition is quite coarse tuning. Do you have any idea?

**Review by junyong-sim — APPROVED** [review]
LGTM

**Comment by junyong-sim** [comment]
> According to https://en.wikipedia.org/wiki/Lux, 320–500 is typical office lighting I agree that current condition is quite coarse tuning. Do you have any idea?

No, but, your new commit looks good to me. :)

**Pull request merged**
